export const projects = [
  {
    id: 1,
    name: "Pano Aqui",
    mapPositionTop: 0,
    mapPositionLeft: 100,
    province: "Sindh",
    description: "Pano Akil, Sindh is an off-grid village in the southern most province of Pakistan where there is extreme heat, no electricity, and a lack of clean water supply. Living there are pockets of communities doing their best to adapt with this harsh environment. Our projects have brought development to these remote populations so they are able to enjoy all aspects of life without having to worry about something as basic as a working lightbulb or a fan to cool down from the rough climate. We have been able to implement 45 solar units to the communities living in Pano Akil. Additionally, we were also able to distribute units to a neighboring Hindu village, power a mosque, and teach the community about the benefits of the project. We are currently in the process of sourcing 15 more solar units at which point the entire village will have access to sustainable energy in their homes.",
    dateCompleted: "June 2018",
    imgUrlOne: "https://res.cloudinary.com/nineteesvintage/image/upload/v1567947199/Sunny%20Side%20Up/People/Samir_photo.jpg",
    imgUrlTwo: "https://res.cloudinary.com/nineteesvintage/image/upload/v1567947199/Sunny%20Side%20Up/People/Samir_photo.jpg",
    imgUrlThree: "https://res.cloudinary.com/nineteesvintage/image/upload/v1567947199/Sunny%20Side%20Up/People/Samir_photo.jpg",
    imgUrlFour: "https://res.cloudinary.com/nineteesvintage/image/upload/v1567947199/Sunny%20Side%20Up/People/Samir_photo.jpg",
    googleMapIFrameURL: "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ7T-hvVeINjkRN8OrhhJLlRo&key=AIzaSyBjdnNT03YgqFITKfUwxNERTS7qetWHVMo",
  },
  {
    id: 2,
    name: "Multan",
    mapPositionTop: 100,
    mapPositionLeft: 200,
    province: "",
    description: "",
    dateCompleted: "",
    imgUrlOne: "",
    imgUrlTwo: "",
    imgUrlThree: "",
    imgUrlFour: "",
    googleMapIFrameURL: "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ2afeeFcxOzkRL9RVTscv17o&key=AIzaSyBjdnNT03YgqFITKfUwxNERTS7qetWHVMo",
  },
];
